<h2><?php echo $view['title']; ?></h2>
<form action="/person/edit/' . $personId . '" method="post">
   <table class="table" style="width:auto">
       <tbody>
           <?php foreach($view['row'] as $key => $value) { ?>
               <tr>
                  <th style="text-align:right"><?php echo $key ?>:</th>
                  <td><input name="name" type="text" size="30" maxlength="30" value="<?php echo $value ?>"></td>
               </tr>
           <?php } ?>
           <tr><td><input type="button" name="back" value=" Abbrechen " onclick="goBack()"></td><td><input type="submit" value=" Speichern "></td></tr>
       </tbody>
   </table>
</form>
<a href="/person/<?php echo $view['row']['id']; ?>/edit">Bearbeiten</a><br>
