<h2><?php echo $view['title']; ?></h2>
<div align="center">
<form role="form">
   <?php foreach($view['row'] as $key => $value) { ?>
      <div class="row">
      <div class="form-group col-xs-4">
      <label for="<?php echo $key ?>"><?php echo $key ?></label>
      <input type="text" class="form-control" size="30" maxlength="30" id="<?php echo $key ?>" name="<?php echo $key ?>" value="<?php echo $value ?>">
      </div>
      </div>
   <?php } ?>
   <button type="button" class="btn" onclick="goBack()">Abbrechen</button>
   <button type="submit" class="btn btn-default">Speichern</button>
</form>
</div>
