<h2><?php echo $view['title']; ?></h2>
<table class="table" style="width:auto">
    <tbody>
        <?php foreach($view['row'] as $key => $value) { ?>
            <tr>
               <th style="text-align:right"><?php echo $key ?>:</th>
               <td><?php echo $value ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<a href="<?php echo $_SERVER['REQUEST_URI']; ?>/edit">Bearbeiten</a><br>
