<h2><?php echo $view['title']; ?></h2>
<table>
   <tr><th><h3><?php echo _('Help'); ?></h3></th></tr>
   <tr><td><p><?php echo sprintf(_('Here comes some introction to this software. For further questions, please %s at %s.'), $view['supportName'], $view['supportMail']); ?></p></td></tr>
   <tr><th><h3><?php echo _('About'); ?></h3></th></tr>
   <tr><th><h3><?php echo _('Here comes a short text about the software project itself.'); ?></h3></th></tr>
</tr></table>

