<table class="table table-hover" style="width:auto">
   <thead>
      <tr>
          <!-- <th><?php echo _('Id'); ?></th> -->
          <th><?php echo _('Date'); ?></th>
          <th><?php echo _('Entity'); ?></th>
          <th><?php echo _('Comment'); ?></th>
          <th><?php echo _('Author'); ?></th>
      </tr>
   </thead>
    <tbody>
        <?php foreach($view['story'] as $history) { ?>
            <tr>
                    <!-- <td><?php echo $history->getId(); ?></td> -->
                    <td><?php echo $history->getDate(); ?></td>
                    <td>
                        <?php echo $history->getKeyCode() ? '<a style="color:black" href="/key/'.$history->getKeyId().'">MC '.$history->getKeyCode().'</a>' : ''; ?>
                        <?php echo $history->getLockCode() ? '<a style="color:black" href="/lock/'.$history->getLockId().'">SC '.$history->getLockCode().'</a>' : ''; ?>
                        <?php echo $history->getPersonName() ? '<a style="color:black" href="/person/'.$history->getPersonId().'">'.$history->getPersonName().'</a>' : ''; ?>
                    </td>
                    <td><?php echo $history->getComment(); ?></td>
                    <td><?php echo $history->getAuthorName() ? '<a style="color:black" href="/person/'.$history->getAuthorId().'">'.$history->getAuthorName().'</a>' : 'unknown ('.$history->getAuthorId().')'; ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
