<table class="table table-hover" style="width:auto">
   <thead>
      <tr>
          <!-- <th><?php echo _('Id'); ?></th> -->
          <th><?php echo _('MC'); ?></th>
          <th><?php echo _('Holder'); ?></th>
          <th><?php echo _('Status'); ?></th>
          <th><?php echo _('Comment'); ?></th>
      </tr>
   </thead>
    <tbody>
        <?php foreach($view['keys'] as $key) { ?>
            <tr>
                    <!-- <td><?php echo $key->getId(); ?></td> -->
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $key->getCode(); ?></td>
                    <td><a href="<?php echo $key->getHolder()->getLocation(); ?>" data-toggle="tooltip" title="<?php echo _('Show person details'); ?>" style="color:black"><?php echo $key->getOwnerName(); ?></a>
                    <?php if($key->getDHolderId()) { ?>
                    <sub> (<span class="glyphicon glyphicon-arrow-right"></span> <a href="<?php echo $key->getDHolder()->getLocation(); ?>" data-toggle="tooltip" title="<?php echo _('Show details of designated holder'); ?>" style="color:black"><?php echo $key->getDHolderName(); ?></a>)</sub>
                    <?php } ?>
                    </td>
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $key->getStatusName(); ?></td>
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in" data-toggle="tooltip" title="<?php echo $key->getComment(); ?>"><?php echo $key->getCommentShort(15); ?></td>
                    <td><a href="<?php echo $key->getLocation(); ?>" data-toggle="tooltip" title="<?php echo _('Show details'); ?>" style="color:black"><span class="glyphicon glyphicon-zoom-in"></span></a></td>
                    <td><a href="<?php echo $key->getLocation(); ?>/edit" data-toggle="tooltip" title="<?php echo _('Edit'); ?>" style="color:black"><span class="glyphicon glyphicon-pencil"></span></a></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

