<?php echo $view['key']; ?>
<a href="/key" data-toggle="tooltip" title="<?php echo _('Back to Keylist'); ?>" style="color:black"><span class="glyphicon glyphicon-list-alt"></span></a>
<?php echo $view['permissions']; ?>
<a href="/key" data-toggle="tooltip" title="<?php echo _('Back to Keylist'); ?>" style="color:black"><span class="glyphicon glyphicon-list-alt"></span></a>
<?php /*
<?php echo $view['denials']; ?>
<a href="/key" data-toggle="tooltip" title="<?php echo _('Back to Keylist'); ?>" style="color:black"><span class="glyphicon glyphicon-list-alt"></span></a>
*/
