<h3 style="color:<?php echo $view['titleColor']; ?>"><?php echo $view['title']; ?></h3>
<a href="<?php echo $view['keyLocation']; ?>/allow" data-toggle="tooltip" title="<?php echo _('Edit'); ?>" style="color:black"><span class="glyphicon glyphicon-pencil"></span></a>
<table class="table table-hover" style="width:auto">
    <thead>
      <!-- <th>Perm Id</th> -->
      <!-- <th>Lock Id</th> -->
      <th><!-- SC --></th>
      <th><!-- Venue --></th>
      <th><?php echo _('Status'); ?></th>
    </thead>
    <tbody>
        <?php foreach($view['locks'] as $perm) { ?>
            <tr onclick="document.location = '/lock/<?php echo $perm->getLockId(); ?>';" style="cursor: zoom-in">
                 <!-- <td><?php echo $perm->getId(); ?></td> -->
                 <!-- <td><?php echo $perm->getLockId(); ?></td> -->
                 <td>SC <?php echo $perm->getLockCode(); ?></td>
                 <td><?php echo $perm->getLockPlace(); ?> <?php echo $perm->getLockName(); ?></td>
                 <td><?php echo $perm->getStatus(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
