<table class="table table-hover" style="width:auto">
   <thead>
      <tr>
          <!-- <th><?php echo _('Id'); ?></th> -->
          <th><?php echo _('MC'); ?></th>
          <th><?php echo _('Holder'); ?></th>
          <th><?php echo _('Status'); ?></th>
          <th><?php echo _('Comment'); ?></th>
      </tr>
   </thead>
    <tbody>
        <?php foreach($view['keys'] as $key) { ?>
            <tr>
                    <!-- <td><?php echo $key->getId(); ?></td> -->
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $key->getCode(); ?></td>
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $key->getOwnerName(); ?></td>
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $key->getStatusName(); ?></td>
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $key->getComment(); ?></td>
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: pointer"><span class="glyphicon glyphicon-zoom-in"></span></td>
                    <td onclick="document.location = '<?php echo $key->getLocation(); ?>/edit';" style="cursor: pointer"><span class="glyphicon glyphicon-pencil"></span></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

