<h3><?php echo $view['title']; ?></h3>
<table class="table table-hover" style="width:auto">
    <tbody>
        <?php foreach($view['locks'] as $perm) { ?>
            <tr>
                 <!-- <td>Id <?php echo $perm->getId(); ?></td> -->
                 <td>SC <?php echo $perm->getLockCode(); ?></td>
                 <td><?php echo $perm->getLockPlace(); ?></td>
                 <td><?php echo $perm->getLockName(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
