<h2><?php echo $view['title']; ?></h2>
<table class="table" style="width:auto" align="center"><tr><td>
<form role="form" method="post">
      <div class="row">
      <div class="form-group">

         <?php if ($view['hasData']) { ?>
         <label for="id"><?php echo _('Id'); ?></label>
         <input type="hidden" class="form-control" maxlength="45" id="id" name="id" value="<?php echo $view['key']->getId(); ?>">
         <p class="form-control-static"><?php echo $view['key']->getId(); ?></p>
         <?php } ?>





         <label for="comment"><?php echo _('Comment'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="comment" name="comment" value="<?php if ($view['hasData']) echo $view['key']->getComment(); ?>">
         <p class="help-block"><?php echo _('A comment or more information about this key'); ?></p>

         <?php if ($view['hasData']) { ?>
            <label for="lastupdate"><?php echo _('Last Update'); ?></label>
            <p class="form-control-static"><?php echo $view['key']->getLastUpdate(); ?></p>
         <?php } ?>

      </div>
      </div>
   <button type="button" class="btn" onclick="goBack()"><?php echo _('Cancel'); ?></button>
   <button type="submit" class="btn btn-default"><?php echo _('Save'); ?></button>
   <br /><br />
      <div class="row">
      <div class="form-group">
         <p style="font-size:1.3em; font-weight:bold"><?php echo _('Internal attributes YOU SHOULD NOT change'); ?></p>

         <label for="elnumber"><?php echo _('elnumber'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="elnumber" name="elnumber" value="<?php if ($view['hasData']) echo $view['key']->getElNumber(); ?>">
         <p class="help-block"><?php echo _('The elnumber of this key'); ?></p>

         <label for="code"><?php echo _('MC'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="code" name="code" value="<?php if ($view['hasData']) echo $view['key']->getCode(); ?>">
         <p class="help-block"><?php echo _('The MC / Code'); ?></p>

         <label for="code"><?php echo _('Type'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="type" name="type" value="<?php if ($view['hasData']) echo $view['key']->getType(); ?>">
         <p class="help-block"><?php echo _('The type'); ?></p>

         <label for="code"><?php echo _('Color'); ?></label>
         <select name="colorid" class="form-control">
         <?php foreach(getColors() as $color) { ?>
           <option value="<?php echo $color['id']; ?>"<?php if($view['key']->getColorId() == $color['id']) echo ' selected' ?>><?php echo $color['name']; ?> (<?php echo $color['colorid']; ?>)</option>
         <?php } ?>
         </select>
         <p class="help-block"><?php echo _('The color of this key'); ?></p>

      </div>
      </div>
</form>
