<h2><?php echo $view['title']; ?></h2>
<table class="table table-hover" style="width:auto">
    <?php if(array_key_exists('headers',$view)) { ?>
        <thead>
            <tr>
                <th><?php echo $header; ?></th>
            </tr>
        </thead>
    <?php } ?>
    <tbody>
        <?php foreach($view['rows'] as $key => $row) { ?>
            <tr onclick="document.location = '<?php echo $view['locations'][$key]; ?>';" style="cursor: zoom-in">
                    <td><?php echo $key->getPerson()->getName(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
