<?php
    echo $view['header'];
    if(isset($view['success'])) { ?>
      <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><span class="glyphicon glyphicon-ok" style="font-size:1.5em"></span> <?php echo $view['success']; ?> <span class="glyphicon glyphicon-ok" style="font-size:1.5em"></span></div><?php
    }
    if(isset($view['danger'])) { ?>
      <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><span class="glyphicon glyphicon-remove" style="font-size:1.5em"></span> <?php echo $view['danger']; ?> </button><span class="glyphicon glyphicon-remove" style="font-size:1.5em"></div><?php
    }
    echo $view['body'];
    echo $view['footer'];
