<?php
    echo $view['header'];
    if(isset($view['success'])) { ?>
      <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><span class="glyphicon glyphicon-ok"></span> <?php echo $view['success']; ?></div><?php
    }
    if(isset($view['danger'])) { ?>
      <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><span class="glyphicon glyphicon-remove"></span> <?php echo $view['danger']; ?></div><?php
    }
    echo $view['body'];
    echo $view['footer'];
