<table class="hovertable listtable">
    <thead>
        <tr>
        <?php foreach($view['headers'] as $header) { ?>
            <th><?php echo $header; ?></th>
        <?php } ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($view['rows'] as $row) { ?>
            <tr onclick="document.location = '<?php echo $row['location']; ?>';" style="cursor: zoom-in">
                <?php foreach($row as $value) { ?>
                    <td><?php echo $value ?></td>
                <?php } ?>
            </tr>
        <?php } ?>
    </tbody>
</table>
