<h2><?php echo $view['lock']->getFullName(); ?></h2>
<table class="table" style="width:auto">
    <tbody>
         <tr>
            <th style="text-align:right"><?php echo _('Id'); ?>:</th>
            <td><?php echo $view['lock']->getId(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Number'); ?>:</th>
            <td><?php echo $view['lock']->getNumber(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('SC'); ?>:</th>
            <td><?php echo $view['lock']->getCode(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Status'); ?>:</th>
            <td><?php echo $view['lock']->getStatus(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Venue'); ?>:</th>
            <td><?php echo $view['lock']->getVenue(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Name'); ?>:</th>
            <td><?php echo $view['lock']->getName(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Electronic'); ?>:</th>
            <td><?php if($view['lock']->getHasBatteries() === '1') { echo _('Yes'); } ?><?php if($view['lock']->getHasBatteries() === '0') { echo _('No'); } ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Type'); ?>:</th>
            <td><?php echo $view['lock']->getType(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Postition'); ?>:</th>
            <td><?php echo $view['lock']->getPosition(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Comment'); ?>:</th>
            <td><?php echo $view['lock']->getComment(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Last Update'); ?>:</th>
            <td><?php echo $view['lock']->getLastUpdate(); ?></td>
         </tr>
 



         <tr><br></tr>
         <tr>
            <td colspan="2" align="center">
               <a href="<?php echo $view['lock']->getLocation(); ?>/edit" data-toggle="tooltip" title="<?php echo _('Edit'); ?>" style="color:black"><span class="glyphicon glyphicon-pencil"></span></a>&nbsp;&nbsp;&nbsp;
               <a href="<?php echo $view['lock']->getLocation(); ?>/addhistory" data-toggle="tooltip" title="<?php echo _('Create History Entry'); ?>" style="color:black"><span class="glyphicon glyphicon-comment"></span></a>&nbsp;&nbsp;&nbsp;
               <a href="<?php echo $view['lock']->getLocation(); ?>/delete" data-toggle="tooltip" title="<?php echo _('Delete'); ?>" style="color:black"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
         </tr>
    </tbody>
</table>
