<h2><?php echo $view['title']; ?></h2>
<table class="table" style="width:auto" align="center"><tr><td>
<form role="form" method="post">
      <div class="row">
      <div class="form-group">

         <?php if ($view['hasData']) { ?>
         <label for="id"><?php echo _('Id'); ?></label>
         <input type="hidden" class="form-control" maxlength="45" id="id" name="id" value="<?php echo $view['lock']->getId(); ?>">
         <p class="form-control-static"><?php echo $view['lock']->getId(); ?></p>
         <?php } ?>



         <label for="status"><?php echo _('Status'); ?></label>
         <select name="statusid" class="form-control">
         <?php foreach(getLockStatuses() as $status) { ?>
           <option value="<?php echo $status['id']; ?>"<?php if($view['hasData'] && $view['lock']->getStatusId() == $status['id']) echo ' selected' ?>><?php echo $status['name']; ?></option>
         <?php } ?>
         </select>
         <p class="help-block"><?php echo _('The current status of this lock'); ?></p>


         <label for="comment"><?php echo _('Comment'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="comment" name="comment" value="<?php if ($view['hasData']) echo $view['lock']->getComment(); ?>">
         <p class="help-block"><?php echo _('A comment or more information about this key'); ?></p>

         <?php if ($view['hasData']) { ?>
            <label for="lastupdate"><?php echo _('Last Update'); ?></label>
            <p class="form-control-static"><?php echo $view['lock']->getLastUpdate(); ?></p>
         <?php } ?>

      </div>
      </div>
   <button type="button" class="btn" onclick="goBack()"><?php echo _('Cancel'); ?></button>
   <button type="submit" class="btn btn-default"><?php echo _('Save'); ?></button>
   <br /><br />
      <div class="row">
      <div class="form-group">
         <p style="font-size:1.3em; font-weight:bold"><?php echo _('Internal attributes YOU SHOULD NOT change'); ?></p>

         <label for="code"><?php echo _('SC'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="code" name="code" value="<?php if ($view['hasData']) echo $view['lock']->getCode(); ?>">
         <p class="help-block"><?php echo _('The \'Schlosscode\' of this lock'); ?></p>

         <label for="venueid"><?php echo _('Venue'); ?></label>
         <select name="venueid" class="form-control">
         <?php foreach(getVenues() as $venue) { ?>
           <option value="<?php echo $venue['id']; ?>"<?php if($view['hasData'] && $view['lock']->getVenueId() == $venue['id']) echo ' selected="selected" selected' ?>><?php echo $venue['name']; ?></option>
         <?php } ?>
         </select>
         <p class="help-block"><?php echo _('Where this lock is located'); ?></p>

         <label for="hasbatteries"><?php echo _('Electronic'); ?></label>
         <select name="hasbatteries" class="form-control">
           <option value=""<?php if($view['hasData'] && $view['lock']->getHasBatteries() === '') echo ' selected="selected" selected' ?>><?php echo _('- unknown -'); ?></option>
           <option value="0"<?php if($view['hasData'] && $view['lock']->getHasBatteries() === '0') echo ' selected="selected" selected' ?>><?php echo _('No'); ?></option>
           <option value="1"<?php if($view['hasData'] && $view['lock']->getHasBatteries() === '1') echo ' selected="selected" selected' ?>><?php echo _('Yes'); ?></option>
         </select>
         <p class="help-block"><?php echo _('Does this lock have an electronic'); ?></p>

         <label for="name"><?php echo _('Name'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="name" name="name" value="<?php if ($view['hasData']) echo $view['lock']->getName(); ?>">
         <p class="help-block"><?php echo _('The name of the room'); ?></p>

         <label for="number"><?php echo _('Number'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="number" name="number" value="<?php if ($view['hasData']) echo $view['lock']->getNumber(); ?>">
         <p class="help-block"><?php echo _('The alphanumeric number of this lock'); ?></p>

         <label for="type"><?php echo _('Type'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="type" name="type" value="<?php if ($view['hasData']) echo $view['lock']->getType(); ?>">
         <p class="help-block"><?php echo _('The type of this lock'); ?></p>

         <label for="position"><?php echo _('Position'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="position" name="position" value="<?php if ($view['hasData']) echo $view['lock']->getPosition(); ?>">
         <p class="help-block"><?php echo _('The position of the pins in this lock'); ?></p>


      </div>
      </div>
</form>
