<h3 style="color:<?php echo $view['titleColor']; ?>"><?php echo $view['title']; ?></h3>
<a href="<?php echo $view['lockLocation']; ?>/deny" data-toggle="tooltip" title="<?php echo _('Edit'); ?>" style="color:black"><span class="glyphicon glyphicon-pencil"></span></a>
<table class="table table-hover" style="width:auto">
    <thead>
      <th></th>
      <th></th>
      <th><?php echo _('Status'); ?></th>
    </thead>
    <tbody>
        <?php foreach($view['keys'] as $perm) { ?>
            <tr onclick="document.location = '/key/<?php echo $perm->getKeyId(); ?>';" style="cursor: zoom-in">
                 <td>MC <?php echo $perm->getKeyCode(); ?></td>
                 <td><?php echo $perm->getKeyOwner(); ?></td>
                 <td><?php echo $perm->getStatus(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
