<?php echo $view['lock']; ?>
<a href="/lock" data-toggle="tooltip" title="<?php echo _('Back to Locklist'); ?>" style="color:black"><span class="glyphicon glyphicon-list-alt"></span></a>
<?php echo $view['denials']; ?>
<a href="/lock" data-toggle="tooltip" title="<?php echo _('Back to Locklist'); ?>" style="color:black"><span class="glyphicon glyphicon-list-alt"></span></a>
<?php echo $view['allowed']; ?>
<a href="/lock" data-toggle="tooltip" title="<?php echo _('Back to Locklist'); ?>" style="color:black"><span class="glyphicon glyphicon-list-alt"></span></a>
