<h3><?php echo $view['title']; ?></h3>
<table class="table table-hover" style="width:auto">
    <thead>
      <th></th>
      <th></th>
      <th><?php echo _('Status'); ?></th>
    </thead>
    <tbody>
        <?php foreach($view['keys'] as $perm) { ?>
            <tr onclick="document.location = '/key/<?php echo $perm->getKeyId(); ?>';" style="cursor: zoom-in">
                 <td>MC <?php echo $perm->getKeyCode(); ?></td>
                 <td><?php echo $perm->getKeyOwner(); ?></td>
                 <td><?php echo $perm->getStatus(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
