<h2><?php echo $view['title']; ?></h2>
<form role="form" method="post">
<table class="table" align="center"><tr><td>
   <?php foreach($view['perm'] as $perm) { ?>
   <tr>
      <td>
         <label for="<?php echo $perm->getId(); ?>">SC <?php echo $perm->getLockCode().' - '.$perm->getLockName(); ?></label>
      </td>
      <td>
         <select name="<?php echo $perm->getId(); ?>" class="form-control">
         <option>removed</option>
         <option>allowed</option>
         <option>planned</option>
         </select>
      </td>
   </tr>
   <?php } ?>
   <tr>
      <td>
         <button type="button" class="btn" onclick="goBack()"><?php echo _('Cancel'); ?></button>
      </td>
      <td>
         <button type="submit" class="btn btn-default"><?php echo _('Save'); ?></button>
      </td>
   </tr>
</form>
</table>
