<table class="table table-hover" style="width:auto">>
   <thead>
      <tr>
          <!-- <th><?php echo _('Id'); ?></th> -->
          <th><?php echo _('Name'); ?></th>
          <th><?php echo _('Uid'); ?></th>
          <th><?php echo _('UidNumber'); ?></th>
          <th><?php echo _('MdbId'); ?></th>
          <th><?php echo _('Comment'); ?></th>
      </tr>
   </thead>
    <tbody>
        <?php foreach($view['people'] as $person) { ?>
            <tr onclick="document.location = '<?php echo $person->getLocation(); ?>';" style="cursor: zoom-in">
                    <!-- <td><?php echo $person->getId(); ?></td> -->
                    <td><?php echo $person->getName(); ?></td>
                    <td><?php echo $person->getUid(); ?></td>
                    <td><?php echo $person->getUidNumber(); ?></td>
                    <td><?php echo $person->getMdbId(); ?></td>
                    <td><?php echo $person->getComment(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
