<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title"><?php echo sprintf(_('Deletion of %s'), $view['person']->getName()); ?></h3>
  </div>
  <div class="panel-body">
   <?php echo sprintf(_('Do you really want do delete %s'), $view['person']->getName());?>
   <form role="form" method="post">
            <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $view['person']->getId(); ?>">
            <input type="hidden" class="form-control" id="confirm" name="confirm" value="true">
      <button type="button" class="btn" onclick="goBack()"><?php echo _('Cancel'); ?></button>
      <button type="submit" class="btn btn-default"><?php echo _('Delete'); ?></button>
   </form>
  </div>
</div>
<?php echo $view['personDetails']; ?>
