<h3>Schlüssel</h3>
<table class="table table-hover" style="width:auto">
    <tbody>
        <?php foreach($view['keys'] as $key) { ?>
            <tr onclick="document.location = '<?php echo $key->getLocation(); ?>';" style="cursor: zoom-in">
                 <td>MC <?php echo $key->getCode(); ?></td>
                 <td><?php echo $key->getStatusName(); ?></td>
                 <td><?php echo $key->getComment(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
