<h2><?php echo $view['person']->getName(); ?></h2>
<table class="table" style="width:auto">
    <tbody>
         <tr>
            <th style="text-align:right"><?php echo _('Id'); ?>:</th>
            <td><?php echo $view['person']->getId(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Name'); ?>:</th>
            <td><?php echo $view['person']->getName(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Uid'); ?>:</th>
            <td><?php echo $view['person']->getUid(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('UidNumber'); ?>:</th>
            <td><?php echo $view['person']->getUidNumber(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('MdbId'); ?>:</th>
            <td><?php echo $view['person']->getMdbId(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Comment'); ?>:</th>
            <td><?php echo $view['person']->getId(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Last Updated'); ?>:</th>
            <td><?php echo $view['person']->getId(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right">Name:</th>
            <td><?php echo $view['person']->getName(); ?></td>
         </tr>
    </tbody>
</table>
<a href="/person/<?php echo $view['person']->getId(); ?>/edit"><?php echo _('Edit'); ?></a><br>
