<h2><?php echo $view['title']; ?></h2>
<table class="table" style="width:auto" align="center"><tr><td>
<form role="form" method="post">
      <div class="row">
      <div class="form-group">

         <?php if ($view['hasData']) { ?>
         <label for="id"><?php echo _('Id'); ?></label>
         <input type="hidden" class="form-control" maxlength="45" id="id" name="id" value="<?php echo $view['person']->getId(); ?>">
         <p class="form-control-static"><?php echo $view['person']->getId(); ?></p>
         <?php } ?>

         <label for="name"><?php echo _('Name'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="name" name="name" value="<?php if ($view['hasData']) echo $view['person']->getName(); ?>">
         <p class="help-block"><?php echo _('A human readable name of this person.'); ?></p>

         <label for="uid"><?php echo _('Uid'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="uid" name="uid" value="<?php if ($view['hasData']) echo $view['person']->getUid(); ?>">
         <p class="help-block"><?php echo _('The LDAP Username.'); ?></p>

         <label for="uidnumber"><?php echo _('UidNumber'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="uidnumber" name="uidnumber" value="<?php if ($view['hasData']) echo $view['person']->getUidNumber(); ?>">
         <p class="help-block"><?php echo _('The LDAP User Number.'); ?></p>

         <label for="mdbid"><?php echo _('MdbId'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="mdbid" name="mdbid" value="<?php if ($view['hasData']) echo $view['person']->getMdbId(); ?>">
         <p class="help-block"><?php echo _('The member database number.'); ?></p>

         <label for="comment"><?php echo _('Comment'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="comment" name="comment" value="<?php if ($view['hasData']) echo $view['person']->getComment(); ?>">
         <p class="help-block"><?php echo _('A comment or more information about this person.'); ?></p>

         <?php if ($view['hasData']) { ?>
            <label for="name"><?php echo _('Last Update'); ?></label>
            <p class="form-control-static"><?php echo $view['person']->getLastUpdate(); ?></p>
         <?php } ?>

      </div>
      </div>
   <button type="button" class="btn" onclick="goBack()">Abbrechen</button>
   <button type="submit" class="btn btn-default">Speichern</button>
</form>

