<h2><?php echo $view['person']->getName(); ?></h2>
<table class="table" style="width:auto">
    <tbody>
         <tr>
            <th style="text-align:right"><?php echo _('Id'); ?>:</th>
            <td><?php echo $view['person']->getId(); ?></td>
         </tr>



<table class="table" style="width:auto" align="center"><tr><td>
<form role="form" method="post">
      <div class="row">
      <div class="form-group">

         <input type="text" class="form-control" maxlength="45" id="id" name="id" value="<?php /* if (!empty($view['person']->getId())) echo $view['person']->getId(); */ ?>" hidden>


         <label for="name"><?php echo _('Name'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="name" name="name" value="<?php if ($hasData) echo $view['person']->getName(); ?>">

         <label for="name"><?php echo _('Uid'); ?></label>
         <input type="text" class="form-control" maxlength="45" id="uid" name="uid" value="<?php if (!empty($view['person'])) echo $view['person']->getUid(); ?>">


      </div>
      </div>
   <button type="button" class="btn" onclick="goBack()">Abbrechen</button>
   <button type="submit" class="btn btn-default">Speichern</button>
</form>
</td></tr></table>



         <tr>
            <th style="text-align:right"><?php echo _('Name'); ?>:</th>
            <td><?php echo $view['person']->getName(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Uid'); ?>:</th>
            <td><?php echo $view['person']->getUid(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('UidNumber'); ?>:</th>
            <td><?php echo $view['person']->getUidNumber(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('MdbId'); ?>:</th>
            <td><?php echo $view['person']->getMdbId(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Comment'); ?>:</th>
            <td><?php echo $view['person']->getComment(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Last Updated'); ?>:</th>
            <td><?php echo $view['person']->getLastUpdate(); ?></td>
         </tr>
    </tbody>
</table>
<a href="<?php echo $view['person']->getLocation(); ?>/edit"><?php echo _('Edit'); ?></a><br>
