<table class="table table-hover" style="width:auto">
   <thead>
      <tr>
          <!-- <th><?php echo _('Id'); ?></th> -->
          <th><?php echo _('Name'); ?></th>
          <th><?php echo _('Uid'); ?></th>
          <!-- <th><?php echo _('UidNumber'); ?></th> -->
          <!-- <th><?php echo _('MdbId'); ?></th> -->
          <th><?php echo _('# of Keys'); ?></th>
          <th><?php echo _('Comment'); ?></th>
      </tr>
   </thead>
    <tbody>
        <?php foreach($view['people'] as $person) { ?>
            <tr>
                    <!-- <td><?php echo $person->getId(); ?></td> -->
                    <td onclick="document.location = '<?php echo $person->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $person->getName(); ?></td>
                    <td onclick="document.location = '<?php echo $person->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $person->getUid(); ?></td>
                    <!-- <td><?php echo $person->getUidNumber(); ?></td> -->
                    <!-- <td><?php echo $person->getMdbId(); ?></td> -->
                    <td onclick="document.location = '<?php echo $person->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $person->getNumberOfKeys(); ?></td>
                    <td onclick="document.location = '<?php echo $person->getLocation(); ?>';" style="cursor: zoom-in"><?php echo $person->getComment(); ?></td>
                    <td onclick="document.location = '<?php echo $person->getLocation(); ?>';" style="cursor: pointer"><span class="glyphicon glyphicon-zoom-in"></span></td>
                    <td onclick="document.location = '<?php echo $person->getLocation(); ?>/edit';" style="cursor: pointer"><span class="glyphicon glyphicon-pencil"></span></td>
                    <td onclick="document.location = '<?php echo $person->getLocation(); ?>/delete';" style="cursor: pointer"><span class="glyphicon glyphicon-trash"></span></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
