<h2><?php echo $view['person']->getName(); ?></h2>
<table class="table" style="width:auto">
    <tbody>
         <tr>
            <th style="text-align:right"><?php echo _('Id'); ?>:</th>
            <td><?php echo $view['person']->getId(); ?></td>
         </tr>
         <tr>
            <th style="text-align:right"><?php echo _('Name'); ?>:</th>
            <td><?php echo $view['person']->getName(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Uid'); ?>:</th>
            <td><?php echo $view['person']->getUid(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('UidNumber'); ?>:</th>
            <td><?php echo $view['person']->getUidNumber(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('MdbId'); ?>:</th>
            <td><?php echo $view['person']->getMdbId(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Comment'); ?>:</th>
            <td><?php echo $view['person']->getComment(); ?></td>
         </tr>         <tr>
            <th style="text-align:right"><?php echo _('Last Updated'); ?>:</th>
            <td><?php echo $view['person']->getLastUpdate(); ?></td>
         </tr>
         <tr><br></tr>
         <tr>
            <td align="center"><a href="<?php echo $view['person']->getLocation(); ?>/edit" data-toggle="tooltip" title="<?php echo _('Edit'); ?>" style="color:black"><span class="glyphicon glyphicon-pencil"></span></a></td>
            <td align="center"><a href="<?php echo $view['person']->getLocation(); ?>/delete" data-toggle="tooltip" title="<?php echo _('Delete'); ?>" style="color:black"><span class="glyphicon glyphicon-trash"></span></a></td>
         </tr>
    </tbody>
</table>
