<h2><?php echo _('Deletion of Person'); ?></h2>
<?php echo $view['personDetails']; ?>
<?php if ($view['deletable']) { ?>
<p>Soll die Person wirklich geloescht werden.</p>
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title"><?php echo sprintf(_('Deletion of %s'), $view['person']->getName()); ?></h3>
  </div>
  <div class="panel-body">
    <?php echo sprintf(_('Do you really want do delete %s'), $view['person']->getName());?>
  </div>
</div>
<?php } else { ?>
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><?php echo sprintf(_('Can not delete %s'), $view['person']->getName()); ?></h3>
  </div>
  <div class="panel-body">
    <?php echo sprintf(_('%s can not be deleted (he probably still owns keys).'), $view['person']->getName());?>
  </div>
</div>
<?php } ?>
<br><p onclick="goBack()" style="cursor: pointer"><?php echo _('Back'); ?></p>
